import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@tabler/core/dist/css/tabler.min.css";
import Tabler from "@/components/Tabler";
import Theme from "@/components/Theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sistem Pendukung Keputusan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme/>
        <div className="page">
          <div className="page-wrapper">
            {children}
          </div>
        </div>
        <Tabler/>
      </body>
    </html>
  );
}
